apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager-manifest
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
  labels:
    app: trust-manager-manifest
spec:
  project: infrastructure
  sources:
  - repoURL: https://github.com/vladoz77/k8s-cluster-config.git
    targetRevision: HEAD 
    path: infrastructure/trustmanager/manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
