apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
  labels:
    app: trust-manager
spec:
  project: infrastructure
  sources:
  - repoURL: quay.io/jetstack/charts
    chart: trust-manager
    targetRevision: 0.22.1
    helm:
      releaseName: trust-manager
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
