apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
  labels:
    app: metrics-server
spec:
  project: infrastructure
  sources:
  - repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.13.1
    helm:
      releaseName: metrics-server
      values: |
        nameOverride: metrics-server
        args:
          - --kubelet-insecure-tls
        metrics:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
