apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
  labels:
    app: envoy-gateway-crds
spec:
  project: infrastructure
  source:
    repoURL: registry-1.docker.io/envoyproxy
    chart: gateway-crds-helm
    targetRevision: v1.8.0
    helm:
      releaseName: eg-crds
      parameters:
        - name: crds.gatewayAPI.enabled
          value: "true"
        - name: crds.gatewayAPI.channel
          value: experimental
        - name: crds.envoyGateway.enabled
          value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
